Repository Leets-Official/Gachtaxi-Mobile, pull requests merged in 2025-03, with the labels that each got.

#2 Feat: 기본 상수 정의 및 설정
  .gitignore
  android/app/build.gradle
  lib/common/constants/colors.dart
  lib/common/constants/spacing.dart
  lib/common/constants/typography.dart
  lib/common/layout/default_layout.dart
  lib/common/util/slide_page_route.dart
  lib/domain/home/view/home_screen.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement

#5 Feat: 구글 맵스 설정 및 바텀 시트 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  assets/icons/friend_icon.svg
  assets/icons/manual_matching_icon.svg
  assets/icons/profile_icon.svg
  assets/icons/taxi_off_icon.svg
  assets/icons/taxi_on_icon.svg
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/common/constants/location.dart
  lib/domain/home/components/custom_bottom_nav_bar.dart
  lib/domain/home/components/custom_bottom_sheet.dart
  lib/domain/home/components/custom_top_bar.dart
  lib/domain/home/components/google_maps.dart
  lib/domain/home/providers/sheet_height_provider.dart
  lib/domain/home/providers/sheet_height_provider.g.dart
  lib/domain/home/shared/notifier_icon.dart
  lib/domain/home/view/home_screen.dart
  lib/domain/home/view/tab-view/auto_matching_screen.dart
  lib/domain/home/view/tab-view/friend_list_screen.dart
  lib/domain/home/view/tab-view/manual_matching_screen.dart
  lib/domain/home/view/tab-view/tab_view.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature

#6 Feat: 채팅 입력창, 새 메세지 UI 구현
  .github/ISSUE_TEMPLATE/feature-issue-template.md
  .github/ISSUE_TEMPLATE/fix_report.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
  lib/common/constants/colors.dart
  lib/domain/chat/presentation/state/chat_input_notifier.dart
  lib/domain/chat/presentation/state/chat_input_notifier.g.dart
  lib/domain/chat/presentation/view/chat_screen.dart
  lib/domain/chat/presentation/widget/chat_input.dart
  lib/domain/chat/presentation/widget/chat_new_message.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature

#12 Feat: 자동, 수동 매칭 리스트에서 사용할 카드 UI 구현
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  assets/icons/change_location_icon.svg
  assets/icons/profile_on_icon.svg
  assets/icons/start_to_end_icon.svg
  lib/common/components/button.dart
  lib/common/constants/colors.dart
  lib/common/enums/matching_category.dart
  lib/common/layout/default_layout.dart
  lib/common/model/pageable_model.dart
  lib/domain/home/components/custom_bottom_nav_bar.dart
  lib/domain/home/components/custom_bottom_sheet.dart
  lib/domain/home/components/custom_top_bar.dart
  lib/domain/home/components/matching/auto/expanded_setting_card.dart
  lib/domain/home/components/matching/auto/location_card.dart
  lib/domain/home/components/matching/manual/manual_matching_card.dart
  lib/domain/home/model/manual-matching/manual_matching_response_model.dart
  lib/domain/home/model/manual-matching/manual_matching_room_model.dart
  lib/domain/home/providers/response/manual_matching_data_provider.dart
  lib/domain/home/providers/ui/manual_matching_change_provider.dart
  lib/domain/home/providers/ui/manual_matching_change_provider.g.dart
  lib/domain/home/providers/ui/sheet_height_provider.dart
  lib/domain/home/providers/ui/sheet_height_provider.g.dart
  lib/domain/home/view/home_screen.dart
  lib/domain/home/view/tab-view/auto_matching_screen.dart
  lib/domain/home/view/tab-view/manual_category_view/manual_matching_category_screen.dart
  lib/domain/home/view/tab-view/manual_matching_screen.dart
  lib/domain/home/view/tab-view/tab_view.dart
  pubspec.lock
Labels: ✨Feature

#13 #7 Feat: 로그인 회원가입 UI 구현
  assets/icons/back_icon.svg
  assets/icons/first_landing.png
  assets/icons/google_icon.svg
  assets/icons/kakao_icon.svg
  assets/icons/second_landing.png
  assets/icons/sign_up_taxi.svg
  assets/icons/third_landing.png
  lib/common/components/button.dart
  lib/common/components/input_field.dart
  lib/common/constants/colors.dart
  lib/common/constants/spacing.dart
  lib/common/modal/custom_modal.dart
  lib/domain/landing/components/first_landing_screen.dart
  lib/domain/landing/components/second_landing_screen.dart
  lib/domain/landing/components/third_landing_screen.dart
  lib/domain/landing/view/landing_screen.dart
  lib/domain/sign-up/utils/timer_manager.dart
  lib/domain/sign-up/view/email_verification_screen.dart
  lib/domain/sign-up/view/sign_up_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature, 🎨Style

#10 Feat 입장 퇴장 메시지 UI구현
  assets/icons/unknown.svg
  lib/common/constants/typography.dart
  lib/domain/chat/application/factory/abstract_message_strategy.dart
  lib/domain/chat/application/factory/chat_enter_message_strategy.dart
  lib/domain/chat/application/factory/chat_exit_message_strategy.dart
  lib/domain/chat/application/factory/chat_message_factory.dart
  lib/domain/chat/application/factory/chat_message_strategy.dart
  lib/domain/chat/application/factory/chat_read_strategy.dart
  lib/domain/chat/data/enums/chat_message_type.dart
  lib/domain/chat/data/models/chat_dummy.dart
  lib/domain/chat/data/models/chat_message_model.dart
  lib/domain/chat/presentation/view/chat_screen.dart
  lib/domain/chat/presentation/widget/chat_enter_exit_message.dart
  lib/domain/chat/presentation/widget/chat_message.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature, 🎨Style

#17 Feat: 추가액션 및 채팅창 UI 구현
  android/app/src/main/AndroidManifest.xml
  assets/icons/account_icon.svg
  assets/icons/crown.svg
  assets/icons/exit.svg
  assets/icons/kakaot.png
  assets/icons/matching_stop_icon.svg
  assets/icons/plus_empty_icon.svg
  assets/icons/plus_fill_icon.svg
  assets/icons/tada.png
  assets/icons/tmoney.png
  assets/icons/uber.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/common/components/modal.dart
  lib/common/util/modal_util.dart
  lib/domain/chat/data/models/chat_user.dart
  lib/domain/chat/data/models/chat_user_dummy.dart
  lib/domain/chat/presentation/state/chat_input_action_notifier.dart
  lib/domain/chat/presentation/state/chat_input_text_notifier.dart
  lib/domain/chat/presentation/view/chat_screen.dart
  lib/domain/chat/presentation/view/taxi_call_screen.dart
  lib/domain/chat/presentation/widget/account_modal.dart
  lib/domain/chat/presentation/widget/chat_action_bar.dart
  lib/domain/chat/presentation/widget/chat_input.dart
  lib/domain/chat/presentation/widget/chat_member.dart
  lib/domain/chat/presentation/widget/chat_message.dart
  lib/domain/chat/presentation/widget/chat_profile_modal.dart
  lib/domain/chat/presentation/widget/profile_image.dart
  lib/domain/chat/presentation/widget/taxi_app_button.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature, 🎨Style

#16 #14 Feat: 회원가입 UI 구현
  android/app/src/main/AndroidManifest.xml
  assets/icons/back_icon.svg
  assets/icons/camera_icon.svg
  assets/icons/cancel_image.svg
  assets/icons/modal_next_icon.svg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/common/constants/spacing.dart
  lib/common/modal/custom_modal.dart
  lib/common/modal/term_agreement_modal.dart
  lib/common/util/modal_utils.dart
  lib/domain/sign-up/components/gender_toggle.dart
  lib/domain/sign-up/components/profile_upload.dart
  lib/domain/sign-up/modal/term_agreement_modal.dart
  lib/domain/sign-up/view/email_verification_screen.dart
  lib/domain/sign-up/view/sign_up_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨Feature, 🎨Style

#24 Feat 전역 api client
  lib/common/model/api_response.dart
  lib/common/util/api_client.dart
  lib/common/util/logger.dart
  lib/common/util/token_storage.dart
  lib/main.dart
  pubspec.yaml
Labels: ✨Feature, 🔗API
